"""CachedEmbeddingProvider — CacheKit L1/L2 wrapper around any EmbeddingProvider."""

import asyncio
import logging
from typing import Any

from .protocol import EmbeddingProvider

logger = logging.getLogger(__name__)

try:
    import os

    from cachekit import cache as _cachekit_cache

    _ck_kwargs: dict[str, Any] = {}
    if not os.environ.get("REDIS_URL") and not os.environ.get("CACHEKIT_REDIS_URL"):
        _ck_kwargs["backend"] = None  # L1-only

    _CACHEKIT_AVAILABLE = True
except ImportError:
    _CACHEKIT_AVAILABLE = False


class CachedEmbeddingProvider:
    """Wraps any EmbeddingProvider with CacheKit L1 (in-process) + L2 (Redis) caching.

    Each text is cached individually via CacheKit's decorator. CacheKit handles
    miss-through transparently: on cache miss, it calls the inner provider for
    that single text, stores the result, and returns it.

    Cache key auto-generated by CacheKit includes (text, prompt_name) as function
    parameters. Namespace includes model_name (dimensions omitted to avoid eager
    model loading on LocalProvider).
    """

    def __init__(self, inner: EmbeddingProvider) -> None:
        self._inner = inner
        self._cache_fn = None

        if _CACHEKIT_AVAILABLE:
            # Use model_name only — dimensions are implicit per model and
            # accessing inner.dimensions can trigger eager model load.
            model_slug = inner.model_name.replace("/", "_")
            namespace = f"mcp_memory_embed_{model_slug}"

            @_cachekit_cache(ttl=86400, namespace=namespace, **_ck_kwargs)
            async def _cached_single_embed(text: str, prompt_name: str = "query") -> list[float]:
                """CacheKit-decorated single-text embed. Miss-through to inner provider."""
                result = await inner.embed_batch([text], prompt_name=prompt_name)
                return result[0]

            self._cache_fn = _cached_single_embed

    @property
    def dimensions(self) -> int:
        return self._inner.dimensions

    @property
    def model_name(self) -> str:
        return self._inner.model_name

    async def health_check(self) -> bool:
        """Delegate health_check to inner provider if available."""
        if hasattr(self._inner, "health_check"):
            return await self._inner.health_check()
        return True

    async def embed_batch(
        self,
        texts: list[str],
        prompt_name: str = "query",
    ) -> list[list[float]]:
        if not texts:
            return []

        if not self._cache_fn:
            # CacheKit not available — pass through directly
            return await self._inner.embed_batch(texts, prompt_name=prompt_name)

        # Per-text cache lookup. CacheKit handles miss-through transparently.
        results = await asyncio.gather(*(self._cache_fn(text, prompt_name) for text in texts))
        return list(results)
